### Index for cars
GET http://localhost:3000/cars

### Show for car

GET http://localhost:3000/cars/2

### Cars create

POST http://localhost:3000/cars
Content-Type: application/json

{
  "model": "F150",
  "year": "2015",
  "color": "Silver"
}

### Cars update

PATCH http://localhost:3000/cars/4
Content-Type: application/json

{
  "color": "White"
}

### DELETE CAR

DELETE http://localhost:3000/cars/4

#### Index for races

GET http://localhost:3000/races

### Show race winner
GET http://localhost:3000/races/1